# Generated by Django 4.2.7 on 2023-12-07 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_Data',
            new_name='file_data',
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.folder'),
        ),
    ]
